export default value => {
  switch (value) {
    case '11':
      return "あ"
    case '12':
      return "い"
    case '13':
      return "う"
    case '14':
      return "え"
    case '15':
      return "お"
    case '16':
      return "Ａ"
    case '17':
      return "Ｂ"
    case '18':
      return "Ｃ"
    case '19':
      return "Ｄ"
    case '10':
      return "Ｅ"
    case '21':
      return "か"
    case '22':
      return "き"
    case '23':
      return "く"
    case '24':
      return "け"
    case '25':
      return "こ"
    case '26':
      return "Ｆ"
    case '27':
      return "Ｇ"
    case '28':
      return "Ｈ"
    case '29':
      return "Ｉ"
    case '20':
      return "Ｊ"
    case '31':
      return "さ"
    case '32':
      return "し"
    case '33':
      return "す"
    case '34':
      return "せ"
    case '35':
      return "そ"
    case '36':
      return "Ｋ"
    case '37':
      return "Ｌ"
    case '38':
      return "Ｍ"
    case '39':
      return "Ｎ"
    case '30':
      return "Ｏ"
    case '41':
      return "た"
    case '42':
      return "ち"
    case '43':
      return "つ"
    case '44':
      return "て"
    case '45':
      return "と"
    case '46':
      return "Ｐ"
    case '47':
      return "Ｑ"
    case '48':
      return "Ｒ"
    case '49':
      return "Ｓ"
    case '40':
      return "Ｔ"
    case '51':
      return "な"
    case '52':
      return "に"
    case '53':
      return "ぬ"
    case '54':
      return "ね"
    case '55':
      return "の"
    case '56':
      return "Ｕ"
    case '57':
      return "Ｖ"
    case '58':
      return "Ｗ"
    case '59':
      return "Ｘ"
    case '50':
      return "Ｙ"
    case '61':
      return "は"
    case '62':
      return "ひ"
    case '63':
      return "ふ"
    case '64':
      return "へ"
    case '65':
      return "ほ"
    case '66':
      return "Ｚ"
    case '67':
      return "？"
    case '68':
      return "！"
    case '69':
      return "－"
    case '60':
      return "／"
    case '71':
      return "ま"
    case '72':
      return "み"
    case '73':
      return "む"
    case '74':
      return "め"
    case '75':
      return "も"
    case '76':
      return "￥"
    case '77':
      return "＆"
    case '78':
      return "機"
    case '79':
      return "機"
    case '70':
      return "機"
    case '81':
      return "や"
    case '82':
      return "（"
    case '83':
      return "ゆ"
    case '84':
      return "）"
    case '85':
      return "よ"
    case '86':
      return "＊"
    case '87':
      return "＃"
    case '88':
      return "空"
    case '89':
      return "機"
    case '80':
      return "機"
    case '91':
      return "ら"
    case '92':
      return "り"
    case '93':
      return "る"
    case '94':
      return "れ"
    case '95':
      return "ろ"
    case '96':
      return "１"
    case '97':
      return "２"
    case '98':
      return "３"
    case '99':
      return "４"
    case '90':
      return "５"
    case '01':
      return "わ"
    case '02':
      return "を"
    case '03':
      return "ん"
    case '04':
      return "゛"
    case '05':
      return "゜"
    case '06':
      return "６"
    case '07':
      return "７"
    case '08':
      return "８"
    case '09':
      return "９"
    case '00':
      return "０"
    default:
      return value
  }
}
